### ISSUE TITLE
Dall-e needs subscription?

### ISSUE THREAD

**Issue by sparking-meteor** [nextgen-user/freegpt4plus#1]
Hi, I've been using your software for a lot of things and it has been like the best thing i descovered since i got invested in AIs world, it's like a fever dream (no kidding)
Among the features I've been trying there's one that surprised me a lot, image generation "/draw"... it works godly when using Prodia, so many models to pick from and the ability to adjust the configuration parameters in a simple and intuitive way is amazing, but I couldn't get Dalle generations to work: it returns the following error:

[Issue] Sorry, I couldn't create an image for you. OpenAI image generation: [Issue] OpenAI/openai: Not Found - "https://opengpt-4ik5.onrender.com/v1/images/generations" cannot be found by the server

I suspect that, effectively, I need a own api key to make it work but haven't found anything related to it so far, so I just assumed it was given free like all the other things

**Comment by vaibhavard** [comment]
Hi @sparking-meteor  , Support for generating images has not yet been added  , and there are no plans for that yet (sorry :<)
Though i am glad you tried out coolagi.. If there are any other requests , feel free to let me know,
Thanks

**Comment by nextgen-user** [comment]
Closing this as this is currently not a priority.Might reopen if i gain support for this :)
