### ISSUE TITLE
[Bug] Site not working.

### ISSUE THREAD

**Issue by ramazansancar** [nextgen-user/freegpt4plus#2]
https://coolagi.vercel.app/

![image](https://github.com/nextgen-user/CoolAGI/assets/8878055/efbd8dae-3234-4e51-b162-2cdd44cd6186)

**Comment by nextgen-user** [comment]
The site was temporarily suspended [For about 2 hours] due to a DDOS attack.The site is live again Now,
![image](https://github.com/nextgen-user/CoolAGI/assets/57561743/10901a99-d657-4405-8788-0e78a421b80e)
